nohup: ignoring input
INFO:     Will watch for changes in these directories: ['/workspaces/synapse-backend-agents-jc']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [31026] using StatReload
/usr/local/python/3.12.1/lib/python3.12/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:
* 'schema_extra' has been renamed to 'json_schema_extra'
  warnings.warn(message, UserWarning)
INFO:     Started server process [31028]
INFO:     Waiting for application startup.
INFO:src.synapse.main:üöÄ Iniciando SynapScale Backend API...
INFO:src.synapse.main:‚úÖ Todas as configura√ß√µes cr√≠ticas est√£o definidas
Aviso: Erros de configura√ß√£o: Configura√ß√£o SMTP necess√°ria para notifica√ß√µes por email
2025-06-03 22:34:36,144 INFO sqlalchemy.engine.Engine BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
2025-06-03 22:34:36,145 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("users")
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("users")
2025-06-03 22:34:36,145 INFO sqlalchemy.engine.Engine [raw sql] ()
INFO:sqlalchemy.engine.Engine:[raw sql] ()
2025-06-03 22:34:36,148 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("refresh_tokens")
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("refresh_tokens")
2025-06-03 22:34:36,148 INFO sqlalchemy.engine.Engine [raw sql] ()
INFO:sqlalchemy.engine.Engine:[raw sql] ()
2025-06-03 22:34:36,149 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("password_reset_tokens")
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("password_reset_tokens")
2025-06-03 22:34:36,149 INFO sqlalchemy.engine.Engine [raw sql] ()
INFO:sqlalchemy.engine.Engine:[raw sql] ()
2025-06-03 22:34:36,149 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("email_verification_tokens")
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("email_verification_tokens")
2025-06-03 22:34:36,150 INFO sqlalchemy.engine.Engine [raw sql] ()
INFO:sqlalchemy.engine.Engine:[raw sql] ()
2025-06-03 22:34:36,150 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("user_variables")
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("user_variables")
2025-06-03 22:34:36,151 INFO sqlalchemy.engine.Engine [raw sql] ()
INFO:sqlalchemy.engine.Engine:[raw sql] ()
2025-06-03 22:34:36,151 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("files")
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("files")
2025-06-03 22:34:36,151 INFO sqlalchemy.engine.Engine [raw sql] ()
INFO:sqlalchemy.engine.Engine:[raw sql] ()
2025-06-03 22:34:36,152 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("workflows")
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("workflows")
2025-06-03 22:34:36,152 INFO sqlalchemy.engine.Engine [raw sql] ()
INFO:sqlalchemy.engine.Engine:[raw sql] ()
2025-06-03 22:34:36,153 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("workflow_nodes")
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("workflow_nodes")
2025-06-03 22:34:36,153 INFO sqlalchemy.engine.Engine [raw sql] ()
INFO:sqlalchemy.engine.Engine:[raw sql] ()
2025-06-03 22:34:36,153 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("workflow_connections")
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("workflow_connections")
2025-06-03 22:34:36,154 INFO sqlalchemy.engine.Engine [raw sql] ()
INFO:sqlalchemy.engine.Engine:[raw sql] ()
2025-06-03 22:34:36,154 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("nodes")
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("nodes")
2025-06-03 22:34:36,155 INFO sqlalchemy.engine.Engine [raw sql] ()
INFO:sqlalchemy.engine.Engine:[raw sql] ()
2025-06-03 22:34:36,155 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("node_categories")
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("node_categories")
2025-06-03 22:34:36,155 INFO sqlalchemy.engine.Engine [raw sql] ()
INFO:sqlalchemy.engine.Engine:[raw sql] ()
2025-06-03 22:34:36,156 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("node_templates")
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("node_templates")
2025-06-03 22:34:36,156 INFO sqlalchemy.engine.Engine [raw sql] ()
INFO:sqlalchemy.engine.Engine:[raw sql] ()
2025-06-03 22:34:36,156 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("agents")
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("agents")
2025-06-03 22:34:36,157 INFO sqlalchemy.engine.Engine [raw sql] ()
INFO:sqlalchemy.engine.Engine:[raw sql] ()
2025-06-03 22:34:36,157 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("conversations")
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("conversations")
2025-06-03 22:34:36,158 INFO sqlalchemy.engine.Engine [raw sql] ()
INFO:sqlalchemy.engine.Engine:[raw sql] ()
2025-06-03 22:34:36,158 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("messages")
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("messages")
2025-06-03 22:34:36,158 INFO sqlalchemy.engine.Engine [raw sql] ()
INFO:sqlalchemy.engine.Engine:[raw sql] ()
2025-06-03 22:34:36,159 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("workflow_executions")
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("workflow_executions")
2025-06-03 22:34:36,159 INFO sqlalchemy.engine.Engine [raw sql] ()
INFO:sqlalchemy.engine.Engine:[raw sql] ()
2025-06-03 22:34:36,160 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("node_executions")
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("node_executions")
2025-06-03 22:34:36,160 INFO sqlalchemy.engine.Engine [raw sql] ()
INFO:sqlalchemy.engine.Engine:[raw sql] ()
2025-06-03 22:34:36,160 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("execution_queue")
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("execution_queue")
2025-06-03 22:34:36,161 INFO sqlalchemy.engine.Engine [raw sql] ()
INFO:sqlalchemy.engine.Engine:[raw sql] ()
2025-06-03 22:34:36,161 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("execution_metrics")
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("execution_metrics")
2025-06-03 22:34:36,161 INFO sqlalchemy.engine.Engine [raw sql] ()
INFO:sqlalchemy.engine.Engine:[raw sql] ()
2025-06-03 22:34:36,162 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("workflow_templates")
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("workflow_templates")
2025-06-03 22:34:36,162 INFO sqlalchemy.engine.Engine [raw sql] ()
INFO:sqlalchemy.engine.Engine:[raw sql] ()
2025-06-03 22:34:36,163 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("template_reviews")
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("template_reviews")
2025-06-03 22:34:36,163 INFO sqlalchemy.engine.Engine [raw sql] ()
INFO:sqlalchemy.engine.Engine:[raw sql] ()
2025-06-03 22:34:36,164 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("template_downloads")
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("template_downloads")
2025-06-03 22:34:36,164 INFO sqlalchemy.engine.Engine [raw sql] ()
INFO:sqlalchemy.engine.Engine:[raw sql] ()
2025-06-03 22:34:36,164 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("template_favorites")
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("template_favorites")
2025-06-03 22:34:36,165 INFO sqlalchemy.engine.Engine [raw sql] ()
INFO:sqlalchemy.engine.Engine:[raw sql] ()
2025-06-03 22:34:36,165 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("template_collections")
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("template_collections")
2025-06-03 22:34:36,165 INFO sqlalchemy.engine.Engine [raw sql] ()
INFO:sqlalchemy.engine.Engine:[raw sql] ()
2025-06-03 22:34:36,166 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("template_usage")
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("template_usage")
2025-06-03 22:34:36,166 INFO sqlalchemy.engine.Engine [raw sql] ()
INFO:sqlalchemy.engine.Engine:[raw sql] ()
2025-06-03 22:34:36,167 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("marketplace_components")
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("marketplace_components")
2025-06-03 22:34:36,167 INFO sqlalchemy.engine.Engine [raw sql] ()
INFO:sqlalchemy.engine.Engine:[raw sql] ()
2025-06-03 22:34:36,167 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("component_ratings")
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("component_ratings")
2025-06-03 22:34:36,168 INFO sqlalchemy.engine.Engine [raw sql] ()
INFO:sqlalchemy.engine.Engine:[raw sql] ()
2025-06-03 22:34:36,168 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("component_downloads")
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("component_downloads")
2025-06-03 22:34:36,168 INFO sqlalchemy.engine.Engine [raw sql] ()
INFO:sqlalchemy.engine.Engine:[raw sql] ()
2025-06-03 22:34:36,169 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("component_purchases")
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("component_purchases")
2025-06-03 22:34:36,169 INFO sqlalchemy.engine.Engine [raw sql] ()
INFO:sqlalchemy.engine.Engine:[raw sql] ()
2025-06-03 22:34:36,170 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("component_versions")
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("component_versions")
2025-06-03 22:34:36,170 INFO sqlalchemy.engine.Engine [raw sql] ()
INFO:sqlalchemy.engine.Engine:[raw sql] ()
2025-06-03 22:34:36,170 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("workspaces")
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("workspaces")
2025-06-03 22:34:36,171 INFO sqlalchemy.engine.Engine [raw sql] ()
INFO:sqlalchemy.engine.Engine:[raw sql] ()
2025-06-03 22:34:36,171 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("workspace_members")
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("workspace_members")
2025-06-03 22:34:36,171 INFO sqlalchemy.engine.Engine [raw sql] ()
INFO:sqlalchemy.engine.Engine:[raw sql] ()
2025-06-03 22:34:36,172 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("workspace_projects")
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("workspace_projects")
2025-06-03 22:34:36,172 INFO sqlalchemy.engine.Engine [raw sql] ()
INFO:sqlalchemy.engine.Engine:[raw sql] ()
2025-06-03 22:34:36,172 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("project_collaborators")
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("project_collaborators")
2025-06-03 22:34:36,172 INFO sqlalchemy.engine.Engine [raw sql] ()
INFO:sqlalchemy.engine.Engine:[raw sql] ()
2025-06-03 22:34:36,173 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("workspace_invitations")
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("workspace_invitations")
2025-06-03 22:34:36,173 INFO sqlalchemy.engine.Engine [raw sql] ()
INFO:sqlalchemy.engine.Engine:[raw sql] ()
2025-06-03 22:34:36,173 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("workspace_activities")
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("workspace_activities")
2025-06-03 22:34:36,173 INFO sqlalchemy.engine.Engine [raw sql] ()
INFO:sqlalchemy.engine.Engine:[raw sql] ()
2025-06-03 22:34:36,173 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("project_comments")
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("project_comments")
2025-06-03 22:34:36,174 INFO sqlalchemy.engine.Engine [raw sql] ()
INFO:sqlalchemy.engine.Engine:[raw sql] ()
2025-06-03 22:34:36,174 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("project_versions")
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("project_versions")
2025-06-03 22:34:36,175 INFO sqlalchemy.engine.Engine [raw sql] ()
INFO:sqlalchemy.engine.Engine:[raw sql] ()
2025-06-03 22:34:36,175 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("analytics_events")
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("analytics_events")
2025-06-03 22:34:36,175 INFO sqlalchemy.engine.Engine [raw sql] ()
INFO:sqlalchemy.engine.Engine:[raw sql] ()
2025-06-03 22:34:36,176 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("user_behavior_metrics")
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("user_behavior_metrics")
2025-06-03 22:34:36,176 INFO sqlalchemy.engine.Engine [raw sql] ()
INFO:sqlalchemy.engine.Engine:[raw sql] ()
2025-06-03 22:34:36,177 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("system_performance_metrics")
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("system_performance_metrics")
2025-06-03 22:34:36,177 INFO sqlalchemy.engine.Engine [raw sql] ()
INFO:sqlalchemy.engine.Engine:[raw sql] ()
2025-06-03 22:34:36,177 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("business_metrics")
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("business_metrics")
2025-06-03 22:34:36,178 INFO sqlalchemy.engine.Engine [raw sql] ()
INFO:sqlalchemy.engine.Engine:[raw sql] ()
2025-06-03 22:34:36,178 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("custom_reports")
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("custom_reports")
2025-06-03 22:34:36,179 INFO sqlalchemy.engine.Engine [raw sql] ()
INFO:sqlalchemy.engine.Engine:[raw sql] ()
2025-06-03 22:34:36,179 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("report_executions")
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("report_executions")
2025-06-03 22:34:36,179 INFO sqlalchemy.engine.Engine [raw sql] ()
INFO:sqlalchemy.engine.Engine:[raw sql] ()
2025-06-03 22:34:36,180 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("user_insights")
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("user_insights")
2025-06-03 22:34:36,180 INFO sqlalchemy.engine.Engine [raw sql] ()
INFO:sqlalchemy.engine.Engine:[raw sql] ()
2025-06-03 22:34:36,181 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("analytics_dashboards")
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("analytics_dashboards")
2025-06-03 22:34:36,181 INFO sqlalchemy.engine.Engine [raw sql] ()
INFO:sqlalchemy.engine.Engine:[raw sql] ()
2025-06-03 22:34:36,182 INFO sqlalchemy.engine.Engine COMMIT
INFO:sqlalchemy.engine.Engine:COMMIT
INFO:src.synapse.main:‚úÖ Tabelas do banco de dados criadas/verificadas com sucesso
2025-06-03 22:34:36,183 INFO sqlalchemy.engine.Engine BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
2025-06-03 22:34:36,184 INFO sqlalchemy.engine.Engine SELECT 1
INFO:sqlalchemy.engine.Engine:SELECT 1
2025-06-03 22:34:36,185 INFO sqlalchemy.engine.Engine [generated in 0.00047s] ()
INFO:sqlalchemy.engine.Engine:[generated in 0.00047s] ()
2025-06-03 22:34:36,185 INFO sqlalchemy.engine.Engine ROLLBACK
INFO:sqlalchemy.engine.Engine:ROLLBACK
INFO:src.synapse.main:‚úÖ Conectividade com banco de dados verificada
INFO:src.synapse.main:‚úÖ WebSocket Manager inicializado
INFO:src.synapse.services.execution_service:üöÄ Engine de Execu√ß√£o iniciada com sucesso!
INFO:src.synapse.main:üöÄ Engine de Execu√ß√£o de Workflows inicializada com sucesso
INFO:src.synapse.main:üéâ SynapScale Backend iniciado com sucesso!
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
INFO:     Application startup complete.
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
INFO:src.synapse.main:üì• GET /docs - Client: 189.37.80.142
INFO:src.synapse.main:üì§ GET /docs - Status: 200 - Time: 0.001s
INFO:     189.37.80.142:0 - "GET /docs HTTP/1.1" 200 OK
INFO:src.synapse.main:üì• GET /openapi.json - Client: 189.37.80.142
INFO:src.synapse.main:üì§ GET /openapi.json - Status: 200 - Time: 0.398s
INFO:     189.37.80.142:0 - "GET /openapi.json HTTP/1.1" 200 OK
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
INFO:src.synapse.main:üì• GET / - Client: 127.0.0.1
INFO:src.synapse.main:üì§ GET / - Status: 200 - Time: 0.001s
INFO:     127.0.0.1:59824 - "GET / HTTP/1.1" 200 OK
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
ERROR:src.synapse.services.execution_service:‚ùå Erro no processador de fila: 'generator' object is not an async iterator
WARNING:  StatReload detected changes in 'fix_prisma_schema.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:src.synapse.main:üîÑ Finalizando SynapScale Backend...
INFO:src.synapse.services.execution_service:üõë Engine de Execu√ß√£o parada com sucesso!
INFO:src.synapse.main:‚úÖ Engine de Execu√ß√£o finalizada com sucesso
INFO:src.synapse.main:‚úÖ SynapScale Backend finalizado com sucesso
INFO:     Application shutdown complete.
INFO:     Finished server process [31028]
Process SpawnProcess-2:
Traceback (most recent call last):
  File "/usr/local/python/3.12.1/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/python/3.12.1/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/uvicorn/server.py", line 66, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/uvicorn/server.py", line 70, in serve
    await self._serve(sockets)
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/uvicorn/server.py", line 77, in _serve
    config.load()
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/uvicorn/config.py", line 435, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/workspaces/synapse-backend-agents-jc/src/synapse/main.py", line 18, in <module>
    from src.synapse.database import engine, Base
  File "/workspaces/synapse-backend-agents-jc/src/synapse/database.py", line 12, in <module>
    engine = create_engine(
             ^^^^^^^^^^^^^^
  File "<string>", line 2, in create_engine
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 549, in create_engine
    u = _url.make_url(url)
        ^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/engine/url.py", line 856, in make_url
    return _parse_url(name_or_url)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/engine/url.py", line 922, in _parse_url
    raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Could not parse SQLAlchemy URL from given URL string
Aviso: Erros de configura√ß√£o: Configura√ß√£o SMTP necess√°ria para notifica√ß√µes por email
WARNING:  StatReload detected changes in 'create_simplified_schema.py'. Reloading...
Process SpawnProcess-3:
Traceback (most recent call last):
  File "/usr/local/python/3.12.1/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/python/3.12.1/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/uvicorn/server.py", line 66, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/uvicorn/server.py", line 70, in serve
    await self._serve(sockets)
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/uvicorn/server.py", line 77, in _serve
    config.load()
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/uvicorn/config.py", line 435, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/workspaces/synapse-backend-agents-jc/src/synapse/main.py", line 18, in <module>
    from src.synapse.database import engine, Base
  File "/workspaces/synapse-backend-agents-jc/src/synapse/database.py", line 12, in <module>
    engine = create_engine(
             ^^^^^^^^^^^^^^
  File "<string>", line 2, in create_engine
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 549, in create_engine
    u = _url.make_url(url)
        ^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/engine/url.py", line 856, in make_url
    return _parse_url(name_or_url)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/engine/url.py", line 922, in _parse_url
    raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Could not parse SQLAlchemy URL from given URL string
Aviso: Erros de configura√ß√£o: Configura√ß√£o SMTP necess√°ria para notifica√ß√µes por email
WARNING:  StatReload detected changes in 'generate_full_schema.py'. Reloading...
Process SpawnProcess-4:
Traceback (most recent call last):
  File "/usr/local/python/3.12.1/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/python/3.12.1/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/uvicorn/server.py", line 66, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/uvicorn/server.py", line 70, in serve
    await self._serve(sockets)
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/uvicorn/server.py", line 77, in _serve
    config.load()
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/uvicorn/config.py", line 435, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/workspaces/synapse-backend-agents-jc/src/synapse/main.py", line 18, in <module>
    from src.synapse.database import engine, Base
  File "/workspaces/synapse-backend-agents-jc/src/synapse/database.py", line 12, in <module>
    engine = create_engine(
             ^^^^^^^^^^^^^^
  File "<string>", line 2, in create_engine
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 549, in create_engine
    u = _url.make_url(url)
        ^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/engine/url.py", line 856, in make_url
    return _parse_url(name_or_url)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/engine/url.py", line 922, in _parse_url
    raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Could not parse SQLAlchemy URL from given URL string
Aviso: Erros de configura√ß√£o: Configura√ß√£o SMTP necess√°ria para notifica√ß√µes por email
WARNING:  StatReload detected changes in 'migrate_to_postgres.py'. Reloading...
Process SpawnProcess-5:
Traceback (most recent call last):
  File "/usr/local/python/3.12.1/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/python/3.12.1/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/uvicorn/server.py", line 66, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/uvicorn/server.py", line 70, in serve
    await self._serve(sockets)
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/uvicorn/server.py", line 77, in _serve
    config.load()
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/uvicorn/config.py", line 435, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/workspaces/synapse-backend-agents-jc/src/synapse/main.py", line 18, in <module>
    from src.synapse.database import engine, Base
  File "/workspaces/synapse-backend-agents-jc/src/synapse/database.py", line 12, in <module>
    engine = create_engine(
             ^^^^^^^^^^^^^^
  File "<string>", line 2, in create_engine
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 549, in create_engine
    u = _url.make_url(url)
        ^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/engine/url.py", line 856, in make_url
    return _parse_url(name_or_url)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/engine/url.py", line 922, in _parse_url
    raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Could not parse SQLAlchemy URL from given URL string
Aviso: Erros de configura√ß√£o: Configura√ß√£o SMTP necess√°ria para notifica√ß√µes por email
WARNING:  StatReload detected changes in 'complete_migration.py'. Reloading...
Process SpawnProcess-6:
Traceback (most recent call last):
  File "/usr/local/python/3.12.1/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/python/3.12.1/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/uvicorn/server.py", line 66, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/uvicorn/server.py", line 70, in serve
    await self._serve(sockets)
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/uvicorn/server.py", line 77, in _serve
    config.load()
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/uvicorn/config.py", line 435, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/workspaces/synapse-backend-agents-jc/src/synapse/main.py", line 18, in <module>
    from src.synapse.database import engine, Base
  File "/workspaces/synapse-backend-agents-jc/src/synapse/database.py", line 12, in <module>
    engine = create_engine(
             ^^^^^^^^^^^^^^
  File "<string>", line 2, in create_engine
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 549, in create_engine
    u = _url.make_url(url)
        ^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/engine/url.py", line 856, in make_url
    return _parse_url(name_or_url)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/engine/url.py", line 922, in _parse_url
    raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Could not parse SQLAlchemy URL from given URL string
Aviso: Erros de configura√ß√£o: Configura√ß√£o SMTP necess√°ria para notifica√ß√µes por email
WARNING:  StatReload detected changes in 'clean_schema_postgres.py'. Reloading...
Process SpawnProcess-7:
Traceback (most recent call last):
  File "/usr/local/python/3.12.1/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/python/3.12.1/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/uvicorn/server.py", line 66, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/uvicorn/server.py", line 70, in serve
    await self._serve(sockets)
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/uvicorn/server.py", line 77, in _serve
    config.load()
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/uvicorn/config.py", line 435, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/workspaces/synapse-backend-agents-jc/src/synapse/main.py", line 18, in <module>
    from src.synapse.database import engine, Base
  File "/workspaces/synapse-backend-agents-jc/src/synapse/database.py", line 12, in <module>
    engine = create_engine(
             ^^^^^^^^^^^^^^
  File "<string>", line 2, in create_engine
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 549, in create_engine
    u = _url.make_url(url)
        ^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/engine/url.py", line 856, in make_url
    return _parse_url(name_or_url)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/engine/url.py", line 922, in _parse_url
    raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Could not parse SQLAlchemy URL from given URL string
Aviso: Erros de configura√ß√£o: Configura√ß√£o SMTP necess√°ria para notifica√ß√µes por email
WARNING:  StatReload detected changes in 'generate_full_schema.py'. Reloading...
Process SpawnProcess-8:
Traceback (most recent call last):
  File "/usr/local/python/3.12.1/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/python/3.12.1/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/uvicorn/server.py", line 66, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/uvicorn/server.py", line 70, in serve
    await self._serve(sockets)
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/uvicorn/server.py", line 77, in _serve
    config.load()
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/uvicorn/config.py", line 435, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/workspaces/synapse-backend-agents-jc/src/synapse/main.py", line 18, in <module>
    from src.synapse.database import engine, Base
  File "/workspaces/synapse-backend-agents-jc/src/synapse/database.py", line 12, in <module>
    engine = create_engine(
             ^^^^^^^^^^^^^^
  File "<string>", line 2, in create_engine
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 549, in create_engine
    u = _url.make_url(url)
        ^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/engine/url.py", line 856, in make_url
    return _parse_url(name_or_url)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/engine/url.py", line 922, in _parse_url
    raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Could not parse SQLAlchemy URL from given URL string
Aviso: Erros de configura√ß√£o: Configura√ß√£o SMTP necess√°ria para notifica√ß√µes por email
